export const TRANSACTIONS_GET = 'TRANSACTIONS_GET';
export const TRANSACTIONS_GET_SUCCESS = 'TRANSACTIONS_GET_SUCCESS';
export const TRANSACTIONS_GET_FAILED = 'TRANSACTIONS_GET_FAILED';
export const TRANSACTIONS_SORT = 'TRANSACTIONS_SORT';
export const TRANSACTIONS_SEARCH = 'TRANSACTIONS_SEARCH';
